name: insta_capture
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  screenshot: ^0.1.1
  path_provider: ^1.1.0
  native_device_orientation: ^0.2.0
  modal_progress_hud: ^0.1.3
  flutter_redux: ^0.5.3
  redux: ^3.0.0
  flutter_offline: ^0.2.4+1
  redux_epics: ^0.10.6
  intl: ^0.15.8
  flutter_villains: ^1.2.1
  equatable: ^0.2.6
  image_picker: ^0.6.0+10
  image_gallery_saver: ^1.1.0
  permission: ^0.1.2
  geolocator: ^5.0.1
  location: ^2.3.5
  flutter_email_sender: ^2.0.3
  url_launcher: ^5.0.3
  esys_flutter_share: ^1.0.2
  image_saver: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/camera.png
     - assets/contact.png
     - assets/gallery.png
     - assets/info.png
     - assets/logo.png

  fonts:
     - family: JTLeonor
       fonts:
         - asset: assets/font_assets/JTLEONOR-BOLD_0.OTF
         - asset: assets/font_assets/JTLEONOR-BOLDITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-DEMIBOLD_0.OTF
         - asset: assets/font_assets/JTLEONOR-DEMIBOLDITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-EXTRABOLD_0.OTF
         - asset: assets/font_assets/JTLEONOR-EXTRABOLDITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-EXTRALIGHT_0.OTF
         - asset: assets/font_assets/JTLEONOR-EXTRALIGHTITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-HEAVY_0.OTF
         - asset: assets/font_assets/JTLEONOR-HEAVYITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-LIGHT_0.OTF
         - asset: assets/font_assets/JTLEONOR-LIGHTITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-MEDIUM_0.OTF
         - asset: assets/font_assets/JTLEONOR-MEDIUMITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-REGULAR_0.OTF
         - asset: assets/font_assets/JTLEONOR-REGULARITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-SEMIBOLD_0.OTF
         - asset: assets/font_assets/JTLEONOR-SEMIBOLDITALIC_0.OTF
         - asset: assets/font_assets/JTLEONOR-THIN_0.OTF
         - asset: assets/font_assets/JTLEONOR-THINITALIC_0.OTF



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
